ALTER TABLE build ADD COLUMN mem_peak INTEGER;
ALTER TABLE build ADD COLUMN cpu_user INTEGER;
ALTER TABLE build ADD COLUMN cpu_system INTEGER;
ALTER TABLE build ADD COLUMN io_tbr INTEGER;
ALTER TABLE build ADD COLUMN io_tbw INTEGER;
