name: Try build docker image

on:
  pull_request:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/Dockerfile
          push: false